"""
gRPC ChatService implementation.

Handles the StreamChat RPC:
  1. Authenticate via JWT in gRPC metadata
  2. Load dataset AES key
  3. Tokenize user input with PIIPseudonymizer
  4. Store token_map in Redis for this chat session
  5. Stream tokenized history + message to Ollama
  6. Apply RBAC decryptor to each output chunk
  7. Audit log decrypted tokens
  8. Persist messages to PostgreSQL (tokenized, never plaintext)
"""
import asyncio
import uuid
from datetime import datetime, timezone

import grpc
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from api.config import get_settings
from api.db import AsyncSessionLocal
from api.models import ChatSession, Dataset, EncryptionKey, Message, User
from api.security import decode_access_token, decrypt_aes_key
from api.services.audit import log_decryptions
from api.services.decryptor import get_allowed_entity_types, resolve_tokens
from api.services.ollama import stream_chat
from api.services.tokenizer import tokenize_message

import sys, os
_ROOT = os.path.join(os.path.dirname(__file__), "..", "..", "api", "grpc")
sys.path.insert(0, _ROOT)

# These are generated by protoc — imported at runtime after generation
try:
    from api.grpc import chat_pb2, chat_pb2_grpc
except ImportError:
    chat_pb2 = None
    chat_pb2_grpc = None


async def _get_user(token: str, db: AsyncSession) -> User | None:
    subject = decode_access_token(token)
    if not subject:
        return None
    try:
        user_id = uuid.UUID(subject)
    except ValueError:
        return None
    result = await db.execute(
        select(User).where(User.id == user_id, User.is_active == True)
    )
    return result.scalar_one_or_none()


async def _get_aes_key(dataset_id: uuid.UUID, db: AsyncSession) -> bytes | None:
    result = await db.execute(
        select(EncryptionKey).where(EncryptionKey.dataset_id == dataset_id)
    )
    enc_key = result.scalar_one_or_none()
    if not enc_key:
        return None
    return decrypt_aes_key(enc_key.encrypted_key)


async def _build_ollama_history(session_id: uuid.UUID, db: AsyncSession) -> list[dict]:
    result = await db.execute(
        select(Message)
        .where(Message.session_id == session_id)
        .order_by(Message.created_at)
    )
    return [{"role": m.role, "content": m.content} for m in result.scalars()]


class ChatServicer:
    """Implements ChatService.StreamChat."""

    async def StreamChat(self, request, context):
        settings = get_settings()

        # Extract auth token from gRPC metadata (preferred) or request field (fallback)
        metadata = dict(context.invocation_metadata())
        token = metadata.get("authorization", "").replace("Bearer ", "") or request.auth_token

        async with AsyncSessionLocal() as db:
            user = await _get_user(token, db)
            if not user:
                await context.abort(grpc.StatusCode.UNAUTHENTICATED, "Invalid token")
                return

            # Resolve chat session
            try:
                session_id = uuid.UUID(request.chat_session_id) if request.chat_session_id else None
                dataset_id = uuid.UUID(request.dataset_id) if request.dataset_id else None
            except ValueError:
                await context.abort(grpc.StatusCode.INVALID_ARGUMENT, "Invalid UUID")
                return

            # Create new session if needed
            if not session_id:
                session = ChatSession(
                    user_id=user.id,
                    dataset_id=dataset_id,
                    title=request.message[:60] or "New chat",
                )
                db.add(session)
                await db.flush()
                session_id = session.id
            else:
                result = await db.execute(
                    select(ChatSession).where(
                        ChatSession.id == session_id,
                        ChatSession.user_id == user.id,
                    )
                )
                session = result.scalar_one_or_none()
                if not session:
                    await context.abort(grpc.StatusCode.NOT_FOUND, "Session not found")
                    return

            # Load AES key + dataset model name
            aes_key: bytes | None = None
            dataset_model: str | None = None
            if dataset_id:
                aes_key = await _get_aes_key(dataset_id, db)
                ds_result = await db.execute(
                    select(Dataset).where(Dataset.id == dataset_id)
                )
                ds_obj = ds_result.scalar_one_or_none()
                if ds_obj:
                    dataset_model = ds_obj.model_name

            # Tokenize user message
            user_content = request.message
            token_map: dict[str, str] = {}
            if aes_key:
                user_content, token_map = await asyncio.get_event_loop().run_in_executor(
                    None,
                    tokenize_message,
                    request.message,
                    aes_key,
                    settings.MODEL_PATH,
                )
                # Persist token_map to Redis so decryptor can resolve them
                from src.redis_client import store_token_map
                if token_map:
                    store_token_map(
                        token_map=token_map,
                        session_id=str(session_id),
                        filename=f"chat:{session_id}",
                        key_id="chat",
                        url=settings.REDIS_URL,
                    )

            # Persist user message (tokenized)
            db.add(Message(session_id=session_id, role="user", content=user_content))
            await db.commit()

            # Build conversation history for Ollama
            history = await _build_ollama_history(session_id, db)

            # RBAC: determine which entity types this user may see
            allowed = await get_allowed_entity_types(user.id, dataset_id, user.role, db)

            # Load token maps from Redis for decryption
            from src.redis_client import get_token_map
            full_token_map = get_token_map(str(session_id), url=settings.REDIS_URL)

            # Also load dataset-level token map (imported from dump.rdb)
            dataset_token_map: dict[str, str] = {}
            if dataset_id:
                import redis as _redis
                _r = _redis.from_url(settings.REDIS_URL, decode_responses=True)
                try:
                    dataset_token_map = _r.hgetall(f"ds:{dataset_id}:tokenmap") or {}
                finally:
                    _r.close()

            # Stream Ollama response using dataset's model if set
            ollama_model = dataset_model or settings.OLLAMA_MODEL
            assistant_chunks: list[str] = []
            try:
                async for chunk in stream_chat(history, model=ollama_model):
                    resolved = resolve_tokens(
                        chunk, full_token_map, aes_key or b"", allowed, dataset_token_map
                    )
                    await log_decryptions(chunk, resolved, user.id, dataset_id, db)
                    assistant_chunks.append(chunk)  # store tokenized version
                    if chat_pb2:
                        yield chat_pb2.ChatChunk(content=resolved, done=False)
            except Exception as exc:
                if chat_pb2:
                    yield chat_pb2.ChatChunk(content="", done=True, error=str(exc))
                return

            # Persist assistant message (tokenized)
            if assistant_chunks:
                full_assistant = "".join(assistant_chunks)
                db.add(Message(session_id=session_id, role="assistant", content=full_assistant))
                # Update session title after first exchange if still default
                if session.title and len(session.title) < 64:
                    pass  # keep existing title
                session.updated_at = datetime.now(timezone.utc)
                await db.commit()

            if chat_pb2:
                yield chat_pb2.ChatChunk(content="", done=True)


def create_grpc_server(port: int):
    """Build and return a configured gRPC async server."""
    if chat_pb2_grpc is None:
        raise RuntimeError("gRPC stubs not generated. Run: python -m grpc_tools.protoc ...")

    server = grpc.aio.server()
    chat_pb2_grpc.add_ChatServiceServicer_to_server(ChatServicer(), server)
    server.add_insecure_port(f"[::]:{port}")
    return server
