# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: chat.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'chat.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nchat.proto\x12\x04\x63hat\"_\n\x0b\x43hatRequest\x12\x17\n\x0f\x63hat_session_id\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x12\n\ndataset_id\x18\x03 \x01(\t\x12\x12\n\nauth_token\x18\x04 \x01(\t\"9\n\tChatChunk\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\x12\x0c\n\x04\x64one\x18\x02 \x01(\x08\x12\r\n\x05\x65rror\x18\x03 \x01(\t2A\n\x0b\x43hatService\x12\x32\n\nStreamChat\x12\x11.chat.ChatRequest\x1a\x0f.chat.ChatChunk0\x01\x42\x18\n\x0b\x61i.tux.chatB\tChatProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chat_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013ai.tux.chatB\tChatProto'
  _globals['_CHATREQUEST']._serialized_start=20
  _globals['_CHATREQUEST']._serialized_end=115
  _globals['_CHATCHUNK']._serialized_start=117
  _globals['_CHATCHUNK']._serialized_end=174
  _globals['_CHATSERVICE']._serialized_start=176
  _globals['_CHATSERVICE']._serialized_end=241
# @@protoc_insertion_point(module_scope)
